/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessRolesCreateRoleRequest {

    #[serde(rename = "privs", skip_serializing_if = "Option::is_none")]
    pub privs: Option<String>,

    #[serde(rename = "roleid")]
    pub roleid: String,


}

impl AccessRolesCreateRoleRequest {
    pub fn new(roleid: String) -> AccessRolesCreateRoleRequest {
        AccessRolesCreateRoleRequest {
            
            privs: None,
            
            roleid,
            
        }
    }
}


