/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessVerifyVncTicketRequest {

    /// UserId or token
    #[serde(rename = "authid")]
    pub authid: String,

    /// Verify ticket, and check if user have access 'privs' on 'path'
    #[serde(rename = "path")]
    pub path: String,

    /// Verify ticket, and check if user have access 'privs' on 'path'
    #[serde(rename = "privs")]
    pub privs: String,

    /// The VNC ticket.
    #[serde(rename = "vncticket")]
    pub vncticket: String,


}

impl AccessVerifyVncTicketRequest {
    pub fn new(authid: String, path: String, privs: String, vncticket: String) -> AccessVerifyVncTicketRequest {
        AccessVerifyVncTicketRequest {
            
            authid,
            
            path,
            
            privs,
            
            vncticket,
            
        }
    }
}


