/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessDomainsSyncRequest {

    /// If set, does not write anything.
    #[serde(rename = "dry-run", skip_serializing_if = "Option::is_none")]
    pub dry_run: Option<models::PveBoolean>,

    /// Enable newly synced users immediately.
    #[serde(rename = "enable-new")]
    pub enable_new: models::PveBoolean,

    /// DEPRECATED: use 'remove-vanished' instead. If set, uses the LDAP Directory as source of truth, deleting users or groups not returned from the sync and removing all locally modified properties of synced users. If not set, only syncs information which is present in the synced data, and does not delete or modify anything else.
    #[serde(rename = "full")]
    pub full: models::PveBoolean,

    /// DEPRECATED: use 'remove-vanished' instead. Remove ACLs for users or groups which were removed from the config during a sync.
    #[serde(rename = "purge")]
    pub purge: models::PveBoolean,

    /// A semicolon-separated list of things to remove when they or the user vanishes during a sync. The following values are possible: 'entry' removes the user/group when not returned from the sync. 'properties' removes the set properties on existing user/group that do not appear in the source (even custom ones). 'acl' removes acls when the user/group is not returned from the sync. Instead of a list it also can be 'none' (the default).
    #[serde(rename = "remove-vanished")]
    pub remove_vanished: String,

    /// Select what to sync.
    #[serde(rename = "scope")]
    pub scope: models::PveScopeEnum,


}

impl AccessDomainsSyncRequest {
    pub fn new(enable_new: models::PveBoolean, full: models::PveBoolean, purge: models::PveBoolean, remove_vanished: String, scope: models::PveScopeEnum) -> AccessDomainsSyncRequest {
        AccessDomainsSyncRequest {
            
            dry_run: None,
            
            enable_new,
            
            full,
            
            purge,
            
            remove_vanished,
            
            scope,
            
        }
    }
}


