/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessGroupsGetGroupsResponseDataInner {

    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    #[serde(rename = "groupid")]
    pub groupid: String,

    /// list of users which form this group
    #[serde(rename = "users", skip_serializing_if = "Option::is_none")]
    pub users: Option<String>,


}

impl AccessGroupsGetGroupsResponseDataInner {
    pub fn new(groupid: String) -> AccessGroupsGetGroupsResponseDataInner {
        AccessGroupsGetGroupsResponseDataInner {
            
            comment: None,
            
            groupid,
            
            users: None,
            
        }
    }
}


