/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AccessUsersUpdateTokenInfoResponseData {

    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// API token expiration date (seconds since epoch). '0' means no expiration date.
    #[serde(rename = "expire", skip_serializing_if = "Option::is_none")]
    pub expire: Option<i64>,

    /// The full token id. Only set when 'regenerate' was set.
    #[serde(rename = "full-tokenid", skip_serializing_if = "Option::is_none")]
    pub full_tokenid: Option<String>,

    /// Restrict API token privileges with separate ACLs (default), or give full privileges of corresponding user.
    #[serde(rename = "privsep", skip_serializing_if = "Option::is_none")]
    pub privsep: Option<models::PveBoolean>,

    /// API token value used for authentication. Only set when 'regenerate' was set.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,


}

impl AccessUsersUpdateTokenInfoResponseData {
    pub fn new() -> AccessUsersUpdateTokenInfoResponseData {
        AccessUsersUpdateTokenInfoResponseData {
            
            comment: None,
            
            expire: None,
            
            full_tokenid: None,
            
            privsep: None,
            
            value: None,
            
        }
    }
}


