/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterJobsScheduleAnalyzeResponseDataInner {

    /// UNIX timestamp for the run.
    #[serde(rename = "timestamp")]
    pub timestamp: i64,

    /// UTC timestamp for the run.
    #[serde(rename = "utc")]
    pub utc: String,


}

impl ClusterJobsScheduleAnalyzeResponseDataInner {
    pub fn new(timestamp: i64, utc: String) -> ClusterJobsScheduleAnalyzeResponseDataInner {
        ClusterJobsScheduleAnalyzeResponseDataInner {
            
            timestamp,
            
            utc,
            
        }
    }
}


