/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf {

    /// Override for the endpoint settings in the node section.
    #[serde(rename = "endpoint", skip_serializing_if = "Option::is_none")]
    pub endpoint: Option<String>,

    /// The interface of this node that uses this peer definition.
    #[serde(rename = "iface")]
    pub iface: String,

    /// The name of the referenced node section (the external node or the internal peer node).
    #[serde(rename = "node")]
    pub node: String,

    /// The interface of the other node, if it is internal
    #[serde(rename = "node_iface", skip_serializing_if = "Option::is_none")]
    pub node_iface: Option<String>,

    /// Whether routes for the allowed IPs should be created in the kernel routing table.
    #[serde(rename = "skip_route_generation", skip_serializing_if = "Option::is_none")]
    pub skip_route_generation: Option<models::PveBoolean>,

    #[serde(rename = "type")]
    pub r#type: models::PveRoleEnum,


}

impl ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf {
    pub fn new(iface: String, node: String, r#type: models::PveRoleEnum) -> ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf {
        ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf {
            
            endpoint: None,
            
            iface,
            
            node,
            
            node_iface: None,
            
            skip_route_generation: None,
            
            r#type,
            
        }
    }
}


impl ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf {
    /// Serialise this ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `ClusterSdnListAllResponseDataNodesInnerPeersInnerOneOf `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        
        if let Some(ref v) = self.endpoint {
            parts.push(format!("endpoint={}", v));
        }
        
        
        parts.push(format!("iface={}", self.iface));
        
        
        
        parts.push(format!("node={}", self.node));
        
        
        
        if let Some(ref v) = self.node_iface {
            parts.push(format!("node_iface={}", v));
        }
        
        
        if let Some(ref v) = self.skip_route_generation {
            parts.push(format!("skip_route_generation={}", v));
        }
        
        
        parts.push(format!("type={}", self.r#type));
        
        
        parts.join(",")
    }
}

