/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMappingUpdateDirRequest {

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<String>,

    /// Description of the directory mapping
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// A list of maps for the cluster nodes.
    #[serde(rename = "map", skip_serializing_if = "Option::is_none")]
    pub map: Option<Vec<models::ClusterMappingCreateDirRequestMapInner>>,


}

impl ClusterMappingUpdateDirRequest {
    pub fn new() -> ClusterMappingUpdateDirRequest {
        ClusterMappingUpdateDirRequest {
            
            delete: None,
            
            description: None,
            
            digest: None,
            
            map: None,
            
        }
    }
}


