/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMetricsServerIndexResponseDataInner {

    /// Flag to disable the plugin.
    #[serde(rename = "disable")]
    pub disable: models::PveBoolean,

    /// The ID of the entry.
    #[serde(rename = "id")]
    pub id: String,

    /// Server network port
    #[serde(rename = "port")]
    pub port: i64,

    /// Server dns name or IP address
    #[serde(rename = "server")]
    pub server: String,

    /// Plugin type.
    #[serde(rename = "type")]
    pub r#type: String,


}

impl ClusterMetricsServerIndexResponseDataInner {
    pub fn new(disable: models::PveBoolean, id: String, port: i64, server: String, r#type: String) -> ClusterMetricsServerIndexResponseDataInner {
        ClusterMetricsServerIndexResponseDataInner {
            
            disable,
            
            id,
            
            port,
            
            server,
            
            r#type,
            
        }
    }
}


