/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMappingCreateDirRequest {

    /// Description of the directory mapping
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The ID of the directory mapping
    #[serde(rename = "id")]
    pub id: String,

    /// A list of maps for the cluster nodes.
    #[serde(rename = "map")]
    pub map: Vec<models::ClusterMappingCreateDirRequestMapInner>,


}

impl ClusterMappingCreateDirRequest {
    pub fn new(id: String, map: Vec<models::ClusterMappingCreateDirRequestMapInner>) -> ClusterMappingCreateDirRequest {
        ClusterMappingCreateDirRequest {
            
            description: None,
            
            id,
            
            map,
            
        }
    }
}


