/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterNotificationsGetMatcherFieldValuesResponse {

    #[serde(rename = "data")]
    pub data: Vec<models::ClusterNotificationsGetMatcherFieldValuesResponseDataInner>,

    /// Optional total count, present for paginated list responses.
    #[serde(rename = "total", skip_serializing_if = "Option::is_none")]
    pub total: Option<i32>,

    /// Optional change summary returned by some PUT operations (one entry per modified field).
    #[serde(rename = "changes", skip_serializing_if = "Option::is_none")]
    pub changes: Option<serde_json::Value>,


}

impl ClusterNotificationsGetMatcherFieldValuesResponse {
    pub fn new(data: Vec<models::ClusterNotificationsGetMatcherFieldValuesResponseDataInner>) -> ClusterNotificationsGetMatcherFieldValuesResponse {
        ClusterNotificationsGetMatcherFieldValuesResponse {
            
            data,
            
            total: None,
            
            changes: None,
            
        }
    }
}


