/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterCephMetadataResponseDataNodeNode {

    /// GIT commit used for the build.
    #[serde(rename = "buildcommit")]
    pub buildcommit: String,

    #[serde(rename = "version")]
    pub version: Box<models::ClusterCephMetadataResponseDataNodeNodeVersion>,


}

impl ClusterCephMetadataResponseDataNodeNode {
    pub fn new(buildcommit: String, version: models::ClusterCephMetadataResponseDataNodeNodeVersion) -> ClusterCephMetadataResponseDataNodeNode {
        ClusterCephMetadataResponseDataNodeNode {
            
            buildcommit,
            
            version: Box::new(version),
            
        }
    }
}


