/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterSdnUpdateDnsRequest {

    /// A list of settings you want to delete.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<String>,

    /// Prevent changes if current configuration file has a different digest. This can be used to prevent concurrent modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Certificate SHA 256 fingerprint.
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,

    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// the token for unlocking the global SDN configuration
    #[serde(rename = "lock-token", skip_serializing_if = "Option::is_none")]
    pub lock_token: Option<String>,

    #[serde(rename = "reversemaskv6", skip_serializing_if = "Option::is_none")]
    pub reversemaskv6: Option<i64>,

    #[serde(rename = "ttl", skip_serializing_if = "Option::is_none")]
    pub ttl: Option<i64>,

    #[serde(rename = "url", skip_serializing_if = "Option::is_none")]
    pub url: Option<String>,


}

impl ClusterSdnUpdateDnsRequest {
    pub fn new() -> ClusterSdnUpdateDnsRequest {
        ClusterSdnUpdateDnsRequest {
            
            delete: None,
            
            digest: None,
            
            fingerprint: None,
            
            key: None,
            
            lock_token: None,
            
            reversemaskv6: None,
            
            ttl: None,
            
            url: None,
            
        }
    }
}


