/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterHaRelocateResponseDataBlockingResourcesInner {

    /// The reason why the HA resource is blocking the relocation.
    #[serde(rename = "cause")]
    pub cause: models::PveCauseEnum,

    /// The blocking HA resource id
    #[serde(rename = "sid")]
    pub sid: String,


}

impl ClusterHaRelocateResponseDataBlockingResourcesInner {
    pub fn new(cause: models::PveCauseEnum, sid: String) -> ClusterHaRelocateResponseDataBlockingResourcesInner {
        ClusterHaRelocateResponseDataBlockingResourcesInner {
            
            cause,
            
            sid,
            
        }
    }
}


