/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterCephMetadataResponseData {

    /// Metadata servers configured in the cluster and their properties, keyed by '<name>@<host>'.
    #[serde(rename = "mds")]
    pub mds: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMdsValue>,

    /// Managers configured in the cluster and their properties, keyed by '<name>@<host>'.
    #[serde(rename = "mgr")]
    pub mgr: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMgrValue>,

    /// Monitors configured in the cluster and their properties, keyed by '<name>@<host>'.
    #[serde(rename = "mon")]
    pub mon: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMonValue>,

    /// Ceph version installed on the nodes, keyed by node name.
    #[serde(rename = "node")]
    pub node: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataNodeValue>,

    /// OSDs configured in the cluster and their properties.
    #[serde(rename = "osd")]
    pub osd: Vec<models::ClusterCephMetadataResponseDataOsdInner>,


}

impl ClusterCephMetadataResponseData {
    pub fn new(mds: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMdsValue>, mgr: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMgrValue>, mon: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataMonValue>, node: std::collections::HashMap<String, models::ClusterCephMetadataResponseDataNodeValue>, osd: Vec<models::ClusterCephMetadataResponseDataOsdInner>) -> ClusterCephMetadataResponseData {
        ClusterCephMetadataResponseData {
            
            mds,
            
            mgr,
            
            mon,
            
            node,
            
            osd,
            
        }
    }
}


