/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterBulkActionMigrateRequest {

    /// How many parallel tasks at maximum should be started.
    #[serde(rename = "maxworkers", skip_serializing_if = "Option::is_none")]
    pub maxworkers: Option<i64>,

    /// Enable live migration for VMs and restart migration for CTs.
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<models::PveBoolean>,

    /// Target node.
    #[serde(rename = "target")]
    pub target: String,

    /// Only consider guests from this list of VMIDs.
    #[serde(rename = "vms", skip_serializing_if = "Option::is_none")]
    pub vms: Option<Vec<i32>>,

    /// Enable live storage migration for local disk
    #[serde(rename = "with-local-disks", skip_serializing_if = "Option::is_none")]
    pub with_local_disks: Option<models::PveBoolean>,


}

impl ClusterBulkActionMigrateRequest {
    pub fn new(target: String) -> ClusterBulkActionMigrateRequest {
        ClusterBulkActionMigrateRequest {
            
            maxworkers: None,
            
            online: None,
            
            target,
            
            vms: None,
            
            with_local_disks: None,
            
        }
    }
}


