/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterHaDisarmHaRequest {

    /// Controls how HA managed resources are handled while disarmed. The current state of resources is not affected. 'freeze': new commands and state changes are not applied. 'ignore': resources are removed from HA tracking and can be managed as if they were not HA managed.
    #[serde(rename = "resource-mode")]
    pub resource_mode: models::PveResourceModeEnum,


}

impl ClusterHaDisarmHaRequest {
    pub fn new(resource_mode: models::PveResourceModeEnum) -> ClusterHaDisarmHaRequest {
        ClusterHaDisarmHaRequest {
            
            resource_mode,
            
        }
    }
}


