/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMappingCreatePciRequest {

    /// Description of the logical PCI device.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The ID of the logical PCI mapping.
    #[serde(rename = "id")]
    pub id: String,

    /// Marks the device(s) as being able to be live-migrated (Experimental). This needs hardware and driver support to work.
    #[serde(rename = "live-migration-capable", skip_serializing_if = "Option::is_none")]
    pub live_migration_capable: Option<models::PveBoolean>,

    /// A list of maps for the cluster nodes.
    #[serde(rename = "map")]
    pub map: Vec<models::ClusterMappingCreatePciRequestMapInner>,

    /// Marks the device(s) as being capable of providing mediated devices.
    #[serde(rename = "mdev", skip_serializing_if = "Option::is_none")]
    pub mdev: Option<models::PveBoolean>,


}

impl ClusterMappingCreatePciRequest {
    pub fn new(id: String, map: Vec<models::ClusterMappingCreatePciRequestMapInner>) -> ClusterMappingCreatePciRequest {
        ClusterMappingCreatePciRequest {
            
            description: None,
            
            id,
            
            live_migration_capable: None,
            
            map,
            
            mdev: None,
            
        }
    }
}


