/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterAcmeGetDirectoriesResponseDataInner {

    #[serde(rename = "name")]
    pub name: String,

    /// URL of ACME CA directory endpoint.
    #[serde(rename = "url")]
    pub url: String,


}

impl ClusterAcmeGetDirectoriesResponseDataInner {
    pub fn new(name: String, url: String) -> ClusterAcmeGetDirectoriesResponseDataInner {
        ClusterAcmeGetDirectoriesResponseDataInner {
            
            name,
            
            url,
            
        }
    }
}


