/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterMappingCreatePciRequestMapInnerOneOf {

    /// Description of the node specific device.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,

    /// The vendor and device ID that is expected. Used for detecting hardware changes
    #[serde(rename = "id")]
    pub id: String,

    /// The IOMMU group in which the device is to be expected in. Used for detecting hardware changes.
    #[serde(rename = "iommugroup", skip_serializing_if = "Option::is_none")]
    pub iommugroup: Option<i64>,

    /// The cluster node name.
    #[serde(rename = "node")]
    pub node: String,

    /// The path to the device. If the function is omitted, the whole device is mapped. In that case use the attributes of the first device. You can give multiple paths as a semicolon seperated list, the first available will then be chosen on guest start.
    #[serde(rename = "path")]
    pub path: String,

    /// The subsystem vendor and device ID that is expected. Used for detecting hardware changes.
    #[serde(rename = "subsystem-id", skip_serializing_if = "Option::is_none")]
    pub subsystem_id: Option<String>,


}

impl ClusterMappingCreatePciRequestMapInnerOneOf {
    pub fn new(id: String, node: String, path: String) -> ClusterMappingCreatePciRequestMapInnerOneOf {
        ClusterMappingCreatePciRequestMapInnerOneOf {
            
            description: None,
            
            id,
            
            iommugroup: None,
            
            node,
            
            path,
            
            subsystem_id: None,
            
        }
    }
}


impl ClusterMappingCreatePciRequestMapInnerOneOf {
    /// Serialise this ClusterMappingCreatePciRequestMapInnerOneOf into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `ClusterMappingCreatePciRequestMapInnerOneOf `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        
        if let Some(ref v) = self.description {
            parts.push(format!("description={}", v));
        }
        
        
        parts.push(format!("id={}", self.id));
        
        
        
        if let Some(ref v) = self.iommugroup {
            parts.push(format!("iommugroup={}", v));
        }
        
        
        parts.push(format!("node={}", self.node));
        
        
        
        parts.push(format!("path={}", self.path));
        
        
        
        if let Some(ref v) = self.subsystem_id {
            parts.push(format!("subsystem-id={}", v));
        }
        
        parts.join(",")
    }
}

