/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner {

    /// The volumes of the guest with the information if they will be included in backups.
    #[serde(rename = "children", skip_serializing_if = "Option::is_none")]
    pub children: Option<Vec<models::ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInnerChildrenInner>>,

    /// VMID of the guest.
    #[serde(rename = "id")]
    pub id: i64,

    /// Name of the guest
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,

    /// Type of the guest, VM, CT or unknown for removed but not purged guests.
    #[serde(rename = "type")]
    pub r#type: models::PveClusterBackupTypeEnum,


}

impl ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner {
    pub fn new(id: i64, r#type: models::PveClusterBackupTypeEnum) -> ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner {
        ClusterBackupGetVolumeBackupIncludedResponseDataChildrenInner {
            
            children: None,
            
            id,
            
            name: None,
            
            r#type,
            
        }
    }
}


