/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ClusterSdnLockRequest {

    /// if true, allow acquiring lock even though there are pending changes
    #[serde(rename = "allow-pending", skip_serializing_if = "Option::is_none")]
    pub allow_pending: Option<models::PveBoolean>,


}

impl ClusterSdnLockRequest {
    pub fn new() -> ClusterSdnLockRequest {
        ClusterSdnLockRequest {
            
            allow_pending: None,
            
        }
    }
}


