/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LxcRemoteMigrateVmRequest {

    /// Override I/O bandwidth limit (in KiB/s).
    #[serde(rename = "bwlimit", skip_serializing_if = "Option::is_none")]
    pub bwlimit: Option<f64>,

    /// Delete the original CT and related data after successful migration. By default the original CT is kept on the source cluster in a stopped state.
    #[serde(rename = "delete", skip_serializing_if = "Option::is_none")]
    pub delete: Option<models::PveBoolean>,

    /// Use online/live migration.
    #[serde(rename = "online", skip_serializing_if = "Option::is_none")]
    pub online: Option<models::PveBoolean>,

    /// Use restart migration
    #[serde(rename = "restart", skip_serializing_if = "Option::is_none")]
    pub restart: Option<models::PveBoolean>,

    /// Mapping from source to target bridges. Providing only a single bridge ID maps all source bridges to that bridge. Providing the special value '1' will map each source bridge to itself.
    #[serde(rename = "target-bridge")]
    pub target_bridge: String,

    /// Remote target endpoint
    #[serde(rename = "target-endpoint")]
    pub target_endpoint: String,

    /// Mapping from source to target storages. Providing only a single storage ID maps all source storages to that storage. Providing the special value '1' will map each source storage to itself.
    #[serde(rename = "target-storage")]
    pub target_storage: String,

    /// The (unique) ID of the VM.
    #[serde(rename = "target-vmid", skip_serializing_if = "Option::is_none")]
    pub target_vmid: Option<i32>,

    /// Timeout in seconds for shutdown for restart migration
    #[serde(rename = "timeout", skip_serializing_if = "Option::is_none")]
    pub timeout: Option<i64>,


}

impl LxcRemoteMigrateVmRequest {
    pub fn new(target_bridge: String, target_endpoint: String, target_storage: String) -> LxcRemoteMigrateVmRequest {
        LxcRemoteMigrateVmRequest {
            
            bwlimit: None,
            
            delete: None,
            
            online: None,
            
            restart: None,
            
            target_bridge,
            
            target_endpoint,
            
            target_storage,
            
            target_vmid: None,
            
            timeout: None,
            
        }
    }
}


