/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// LxcMigrateVmPreconditionResponseDataNotAllowedNodes : List of not allowed nodes with additional information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LxcMigrateVmPreconditionResponseDataNotAllowedNodes {

    /// HA resources, which are blocking the container from being migrated to the node.
    #[serde(rename = "blocking-ha-resources", skip_serializing_if = "Option::is_none")]
    pub blocking_ha_resources: Option<Vec<models::ClusterHaMigrateResponseDataBlockingResourcesInner>>,


}

impl LxcMigrateVmPreconditionResponseDataNotAllowedNodes {
    /// List of not allowed nodes with additional information.
    pub fn new() -> LxcMigrateVmPreconditionResponseDataNotAllowedNodes {
        LxcMigrateVmPreconditionResponseDataNotAllowedNodes {
            
            blocking_ha_resources: None,
            
        }
    }
}


