/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LxcVncproxyRequest {

    /// sets the height of the console in pixels.
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<i32>,

    /// use websocket instead of standard VNC.
    #[serde(rename = "websocket", skip_serializing_if = "Option::is_none")]
    pub websocket: Option<models::PveBoolean>,

    /// sets the width of the console in pixels.
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<i32>,


}

impl LxcVncproxyRequest {
    pub fn new() -> LxcVncproxyRequest {
        LxcVncproxyRequest {
            
            height: None,
            
            websocket: None,
            
            width: None,
            
        }
    }
}


