/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LxcVmStartRequest {

    /// If set, enables very verbose debug log-level on start.
    #[serde(rename = "debug", skip_serializing_if = "Option::is_none")]
    pub debug: Option<models::PveBoolean>,

    /// Ignore locks - only root is allowed to use this option.
    #[serde(rename = "skiplock", skip_serializing_if = "Option::is_none")]
    pub skiplock: Option<models::PveBoolean>,


}

impl LxcVmStartRequest {
    pub fn new() -> LxcVmStartRequest {
        LxcVmStartRequest {
            
            debug: None,
            
            skiplock: None,
            
        }
    }
}


