/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct LxcSnapshotCmdIdxResponseDataInner {

    /// URL slug of the child resource (inferred from PVE HATEOAS link).
    #[serde(rename = "cmd")]
    pub cmd: String,


}

impl LxcSnapshotCmdIdxResponseDataInner {
    pub fn new(cmd: String) -> LxcSnapshotCmdIdxResponseDataInner {
        LxcSnapshotCmdIdxResponseDataInner {
            
            cmd,
            
        }
    }
}


