/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksGetZfsResponseDataInner {

    #[serde(rename = "alloc")]
    pub alloc: i64,

    #[serde(rename = "dedup")]
    pub dedup: f64,

    #[serde(rename = "frag")]
    pub frag: i64,

    #[serde(rename = "free")]
    pub free: i64,

    #[serde(rename = "health")]
    pub health: String,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "size")]
    pub size: i64,


}

impl NodesDisksGetZfsResponseDataInner {
    pub fn new(alloc: i64, dedup: f64, frag: i64, free: i64, health: String, name: String, size: i64) -> NodesDisksGetZfsResponseDataInner {
        NodesDisksGetZfsResponseDataInner {
            
            alloc,
            
            dedup,
            
            frag,
            
            free,
            
            health,
            
            name,
            
            size,
            
        }
    }
}


