/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseData {

    /// Common digest of all files.
    #[serde(rename = "digest")]
    pub digest: String,

    /// List of problematic repository files.
    #[serde(rename = "errors")]
    pub errors: Vec<models::NodesAptRepositoriesResponseDataErrorsInner>,

    /// List of parsed repository files.
    #[serde(rename = "files")]
    pub files: Vec<models::NodesAptRepositoriesResponseDataFilesInner>,

    /// Additional information/warnings for APT repositories.
    #[serde(rename = "infos")]
    pub infos: Vec<models::NodesAptRepositoriesResponseDataInfosInner>,

    /// List of standard repositories and their configuration status
    #[serde(rename = "standard-repos")]
    pub standard_repos: Vec<models::NodesAptRepositoriesResponseDataStandardReposInner>,


}

impl NodesAptRepositoriesResponseData {
    pub fn new(digest: String, errors: Vec<models::NodesAptRepositoriesResponseDataErrorsInner>, files: Vec<models::NodesAptRepositoriesResponseDataFilesInner>, infos: Vec<models::NodesAptRepositoriesResponseDataInfosInner>, standard_repos: Vec<models::NodesAptRepositoriesResponseDataStandardReposInner>) -> NodesAptRepositoriesResponseData {
        NodesAptRepositoriesResponseData {
            
            digest,
            
            errors,
            
            files,
            
            infos,
            
            standard_repos,
            
        }
    }
}


