/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStorageIdentityResponseData {

    /// Unique identifier for this storage instance. The exact format and semantics depend on the storage plugin type.
    #[serde(rename = "id")]
    pub id: String,

    /// The type of the storage.
    #[serde(rename = "type")]
    pub r#type: models::PveNodesStorageTypeEnum,


}

impl NodesStorageIdentityResponseData {
    pub fn new(id: String, r#type: models::PveNodesStorageTypeEnum) -> NodesStorageIdentityResponseData {
        NodesStorageIdentityResponseData {
            
            id,
            
            r#type,
            
        }
    }
}


