/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStorageCopyRequest {

    /// Target volume identifier
    #[serde(rename = "target")]
    pub target: String,

    /// Target node. Default is local node.
    #[serde(rename = "target_node", skip_serializing_if = "Option::is_none")]
    pub target_node: Option<String>,


}

impl NodesStorageCopyRequest {
    pub fn new(target: String) -> NodesStorageCopyRequest {
        NodesStorageCopyRequest {
            
            target,
            
            target_node: None,
            
        }
    }
}


