/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStatusStatusResponseData {

    #[serde(rename = "boot-info")]
    pub boot_info: Box<models::NodesStatusStatusResponseDataBootInfo>,

    /// The current cpu usage.
    #[serde(rename = "cpu")]
    pub cpu: f64,

    #[serde(rename = "cpuinfo")]
    pub cpuinfo: Box<models::NodesStatusStatusResponseDataCpuinfo>,

    #[serde(rename = "current-kernel")]
    pub current_kernel: Box<models::NodesStatusStatusResponseDataCurrentKernel>,

    /// An array of load avg for 1, 5 and 15 minutes respectively.
    #[serde(rename = "loadavg")]
    pub loadavg: Vec<String>,

    #[serde(rename = "memory")]
    pub memory: Box<models::NodesStatusStatusResponseDataMemory>,

    /// The PVE version string.
    #[serde(rename = "pveversion")]
    pub pveversion: String,

    #[serde(rename = "rootfs")]
    pub rootfs: Box<models::NodesStatusStatusResponseDataRootfs>,


}

impl NodesStatusStatusResponseData {
    pub fn new(boot_info: models::NodesStatusStatusResponseDataBootInfo, cpu: f64, cpuinfo: models::NodesStatusStatusResponseDataCpuinfo, current_kernel: models::NodesStatusStatusResponseDataCurrentKernel, loadavg: Vec<String>, memory: models::NodesStatusStatusResponseDataMemory, pveversion: String, rootfs: models::NodesStatusStatusResponseDataRootfs) -> NodesStatusStatusResponseData {
        NodesStatusStatusResponseData {
            
            boot_info: Box::new(boot_info),
            
            cpu,
            
            cpuinfo: Box::new(cpuinfo),
            
            current_kernel: Box::new(current_kernel),
            
            loadavg,
            
            memory: Box::new(memory),
            
            pveversion,
            
            rootfs: Box::new(rootfs),
            
        }
    }
}


