/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStorageOciRegistryPullRequest {

    /// Custom destination file name of the OCI image. Caution: This will be normalized!
    #[serde(rename = "filename", skip_serializing_if = "Option::is_none")]
    pub filename: Option<String>,

    /// The reference to the OCI image to download.
    #[serde(rename = "reference")]
    pub reference: String,


}

impl NodesStorageOciRegistryPullRequest {
    pub fn new(reference: String) -> NodesStorageOciRegistryPullRequest {
        NodesStorageOciRegistryPullRequest {
            
            filename: None,
            
            reference,
            
        }
    }
}


