/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptChangeRepositoryRequest {

    /// Digest to detect modifications.
    #[serde(rename = "digest", skip_serializing_if = "Option::is_none")]
    pub digest: Option<String>,

    /// Whether the repository should be enabled or not.
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<models::PveBoolean>,

    /// Index within the file (starting from 0).
    #[serde(rename = "index")]
    pub index: i64,

    /// Path to the containing file.
    #[serde(rename = "path")]
    pub path: String,


}

impl NodesAptChangeRepositoryRequest {
    pub fn new(index: i64, path: String) -> NodesAptChangeRepositoryRequest {
        NodesAptChangeRepositoryRequest {
            
            digest: None,
            
            enabled: None,
            
            index,
            
            path,
            
        }
    }
}


