/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCephCreatemonRequest {

    /// Overwrites autodetected monitor IP address(es). Must be in the public network(s) of Ceph.
    #[serde(rename = "mon-address", skip_serializing_if = "Option::is_none")]
    pub mon_address: Option<String>,


}

impl NodesCephCreatemonRequest {
    pub fn new() -> NodesCephCreatemonRequest {
        NodesCephCreatemonRequest {
            
            mon_address: None,
            
        }
    }
}


