/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTimeTimeResponseData {

    /// Seconds since 1970-01-01 00:00:00 (local time)
    #[serde(rename = "localtime")]
    pub localtime: i64,

    /// Seconds since 1970-01-01 00:00:00 UTC.
    #[serde(rename = "time")]
    pub time: i64,

    /// Time zone
    #[serde(rename = "timezone")]
    pub timezone: String,


}

impl NodesTimeTimeResponseData {
    pub fn new(localtime: i64, time: i64, timezone: String) -> NodesTimeTimeResponseData {
        NodesTimeTimeResponseData {
            
            localtime,
            
            time,
            
            timezone,
            
        }
    }
}


