/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {

    #[serde(rename = "Key")]
    pub key: String,

    #[serde(rename = "Values")]
    pub values: Vec<String>,


}

impl NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
    pub fn new(key: String, values: Vec<String>) -> NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
        NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner {
            
            key,
            
            values,
            
        }
    }
}


