/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesSdnGetContentResponseDataInner {

    /// Status.
    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    /// Status details
    #[serde(rename = "statusmsg", skip_serializing_if = "Option::is_none")]
    pub statusmsg: Option<String>,

    /// Vnet identifier.
    #[serde(rename = "vnet")]
    pub vnet: String,


}

impl NodesSdnGetContentResponseDataInner {
    pub fn new(vnet: String) -> NodesSdnGetContentResponseDataInner {
        NodesSdnGetContentResponseDataInner {
            
            status: None,
            
            statusmsg: None,
            
            vnet,
            
        }
    }
}


