/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCapabilitiesGetCpuResponseDataInner {

    /// True if this is a custom CPU model.
    #[serde(rename = "custom")]
    pub custom: models::PveBoolean,

    /// Name of the CPU model. Identifies it for subsequent API calls. Prefixed with 'custom-' for custom models.
    #[serde(rename = "name")]
    pub name: String,

    /// CPU vendor visible to the guest when this model is selected. Vendor of 'reported-model' in case of custom models.
    #[serde(rename = "vendor")]
    pub vendor: String,


}

impl NodesCapabilitiesGetCpuResponseDataInner {
    pub fn new(custom: models::PveBoolean, name: String, vendor: String) -> NodesCapabilitiesGetCpuResponseDataInner {
        NodesCapabilitiesGetCpuResponseDataInner {
            
            custom,
            
            name,
            
            vendor,
            
        }
    }
}


