/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {

    /// Associated comment
    #[serde(rename = "Comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// List of repository components
    #[serde(rename = "Components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Vec<String>>,

    /// Whether the repository is enabled or not
    #[serde(rename = "Enabled")]
    pub enabled: models::PveBoolean,

    /// Format of the defining file.
    #[serde(rename = "FileType")]
    pub file_type: models::PveFileTypeEnum,

    /// Additional options
    #[serde(rename = "Options", skip_serializing_if = "Option::is_none")]
    pub options: Option<Vec<models::NodesAptRepositoriesResponseDataFilesInnerRepositoriesInnerOptionsInner>>,

    /// List of package distribuitions
    #[serde(rename = "Suites")]
    pub suites: Vec<String>,

    /// List of package types.
    #[serde(rename = "Types")]
    pub types: Vec<models::PveNodesAptInlineEnum>,

    /// List of repository URIs.
    #[serde(rename = "URIs")]
    pub uris: Vec<String>,


}

impl NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
    pub fn new(enabled: models::PveBoolean, file_type: models::PveFileTypeEnum, suites: Vec<String>, types: Vec<models::PveNodesAptInlineEnum>, uris: Vec<String>) -> NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
        NodesAptRepositoriesResponseDataFilesInnerRepositoriesInner {
            
            comment: None,
            
            components: None,
            
            enabled,
            
            file_type,
            
            options: None,
            
            suites,
            
            types,
            
            uris,
            
        }
    }
}


