/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesCephGetMdsResponseDataInner {

    /// Address as advertised by the MDS; Ceph-formatted (typically 'IP:PORT/NONCE').
    #[serde(rename = "addr", skip_serializing_if = "Option::is_none")]
    pub addr: Option<String>,

    /// Full Ceph version string of the MDS daemon.
    #[serde(rename = "ceph_version", skip_serializing_if = "Option::is_none")]
    pub ceph_version: Option<String>,

    /// Short Ceph version string of the MDS daemon (e.g. '19.2.0').
    #[serde(rename = "ceph_version_short", skip_serializing_if = "Option::is_none")]
    pub ceph_version_short: Option<String>,

    /// Set when the MDS's data directory exists on this node.
    #[serde(rename = "direxists", skip_serializing_if = "Option::is_none")]
    pub direxists: Option<models::PveBoolean>,

    /// Name of the CephFS this MDS is bound to; absent or null for standby MDSes not currently serving a rank.
    #[serde(rename = "fs_name", skip_serializing_if = "Option::is_none")]
    pub fs_name: Option<String>,

    /// Host the MDS runs on.
    #[serde(rename = "host", skip_serializing_if = "Option::is_none")]
    pub host: Option<String>,

    /// The name (ID) for the MDS.
    #[serde(rename = "name")]
    pub name: String,

    /// MDS rank within the file system; -1 for standby MDSes not currently bound to a rank.
    #[serde(rename = "rank", skip_serializing_if = "Option::is_none")]
    pub rank: Option<i64>,

    /// Set if a ceph-mds@<id> systemd unit is enabled on the hosting node; absent otherwise.
    #[serde(rename = "service", skip_serializing_if = "Option::is_none")]
    pub service: Option<models::PveBoolean>,

    /// If true, the standby MDS is polling the active MDS for faster recovery (hot standby).
    #[serde(rename = "standby_replay", skip_serializing_if = "Option::is_none")]
    pub standby_replay: Option<models::PveBoolean>,

    /// MDS state: Ceph-reported run state (e.g. 'up:active', 'up:standby', 'up:standby-replay') for daemons known to the cluster; 'stopped' or 'unknown' for configured daemons not visible to the cluster.
    #[serde(rename = "state")]
    pub state: String,


}

impl NodesCephGetMdsResponseDataInner {
    pub fn new(name: String, state: String) -> NodesCephGetMdsResponseDataInner {
        NodesCephGetMdsResponseDataInner {
            
            addr: None,
            
            ceph_version: None,
            
            ceph_version_short: None,
            
            direxists: None,
            
            fs_name: None,
            
            host: None,
            
            name,
            
            rank: None,
            
            service: None,
            
            standby_replay: None,
            
            state,
            
        }
    }
}


