/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesTasksNodeTasksResponseDataInner {

    #[serde(rename = "endtime", skip_serializing_if = "Option::is_none")]
    pub endtime: Option<i64>,

    #[serde(rename = "id")]
    pub id: String,

    #[serde(rename = "node")]
    pub node: String,

    #[serde(rename = "pid")]
    pub pid: i64,

    #[serde(rename = "pstart")]
    pub pstart: i64,

    #[serde(rename = "starttime")]
    pub starttime: i64,

    #[serde(rename = "status", skip_serializing_if = "Option::is_none")]
    pub status: Option<String>,

    #[serde(rename = "type")]
    pub r#type: String,

    #[serde(rename = "upid")]
    pub upid: String,

    #[serde(rename = "user")]
    pub user: String,


}

impl NodesTasksNodeTasksResponseDataInner {
    pub fn new(id: String, node: String, pid: i64, pstart: i64, starttime: i64, r#type: String, upid: String, user: String) -> NodesTasksNodeTasksResponseDataInner {
        NodesTasksNodeTasksResponseDataInner {
            
            endtime: None,
            
            id,
            
            node,
            
            pid,
            
            pstart,
            
            starttime,
            
            status: None,
            
            r#type,
            
            upid,
            
            user,
            
        }
    }
}


