/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptListUpdatesResponseDataInner {

    /// Package Architecture.
    #[serde(rename = "Arch")]
    pub arch: models::PveArchEnum,

    /// Package description.
    #[serde(rename = "Description")]
    pub description: String,

    /// Version for which PVE has already sent an update notification for.
    #[serde(rename = "NotifyStatus", skip_serializing_if = "Option::is_none")]
    pub notify_status: Option<String>,

    /// Old version currently installed.
    #[serde(rename = "OldVersion", skip_serializing_if = "Option::is_none")]
    pub old_version: Option<String>,

    /// Package origin, e.g., 'Proxmox' or 'Debian'.
    #[serde(rename = "Origin")]
    pub origin: String,

    /// Package name.
    #[serde(rename = "Package")]
    pub package: String,

    /// Package priority.
    #[serde(rename = "Priority")]
    pub priority: String,

    /// Package section.
    #[serde(rename = "Section")]
    pub section: String,

    /// Package title.
    #[serde(rename = "Title")]
    pub title: String,

    /// New version to be updated to.
    #[serde(rename = "Version")]
    pub version: String,


}

impl NodesAptListUpdatesResponseDataInner {
    pub fn new(arch: models::PveArchEnum, description: String, origin: String, package: String, priority: String, section: String, title: String, version: String) -> NodesAptListUpdatesResponseDataInner {
        NodesAptListUpdatesResponseDataInner {
            
            arch,
            
            description,
            
            notify_status: None,
            
            old_version: None,
            
            origin,
            
            package,
            
            priority,
            
            section,
            
            title,
            
            version,
            
        }
    }
}


