/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesDisksInitgptRequest {

    /// Block device name
    #[serde(rename = "disk")]
    pub disk: String,

    /// UUID for the GPT table
    #[serde(rename = "uuid", skip_serializing_if = "Option::is_none")]
    pub uuid: Option<String>,


}

impl NodesDisksInitgptRequest {
    pub fn new(disk: String) -> NodesDisksInitgptRequest {
        NodesDisksInitgptRequest {
            
            disk,
            
            uuid: None,
            
        }
    }
}


