/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesStorageGetImportMetadataResponseDataWarningsInner {

    /// Related subject (config) key of warning.
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,

    /// What this warning is about.
    #[serde(rename = "type")]
    pub r#type: models::PveNodesStorageTypeEnum3,

    /// Related subject (config) value of warning.
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,


}

impl NodesStorageGetImportMetadataResponseDataWarningsInner {
    pub fn new(r#type: models::PveNodesStorageTypeEnum3) -> NodesStorageGetImportMetadataResponseDataWarningsInner {
        NodesStorageGetImportMetadataResponseDataWarningsInner {
            
            key: None,
            
            r#type,
            
            value: None,
            
        }
    }
}


