/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesAptRepositoriesResponseDataInfosInner {

    /// Index of the associated repository within the file.
    #[serde(rename = "index")]
    pub index: String,

    /// Kind of the information (e.g. warning).
    #[serde(rename = "kind")]
    pub kind: String,

    /// Information message.
    #[serde(rename = "message")]
    pub message: String,

    /// Path to the associated file.
    #[serde(rename = "path")]
    pub path: String,

    /// Property from which the info originates.
    #[serde(rename = "property", skip_serializing_if = "Option::is_none")]
    pub property: Option<String>,


}

impl NodesAptRepositoriesResponseDataInfosInner {
    pub fn new(index: String, kind: String, message: String, path: String) -> NodesAptRepositoriesResponseDataInfosInner {
        NodesAptRepositoriesResponseDataInfosInner {
            
            index,
            
            kind,
            
            message,
            
            path,
            
            property: None,
            
        }
    }
}


