/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct NodesSdnIpVrfResponseDataInner {

    /// The CIDR of the route table entry.
    #[serde(rename = "ip")]
    pub ip: String,

    /// This route's metric.
    #[serde(rename = "metric")]
    pub metric: i64,

    /// A list of nexthops for the route table entry.
    #[serde(rename = "nexthops")]
    pub nexthops: Vec<String>,

    /// The protocol where this route was learned from (e.g. BGP).
    #[serde(rename = "protocol")]
    pub protocol: String,


}

impl NodesSdnIpVrfResponseDataInner {
    pub fn new(ip: String, metric: i64, nexthops: Vec<String>, protocol: String) -> NodesSdnIpVrfResponseDataInner {
        NodesSdnIpVrfResponseDataInner {
            
            ip,
            
            metric,
            
            nexthops,
            
            protocol,
            
        }
    }
}


