/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterHaTypeTypeEnum2 {
    #[serde(rename = "node-affinity")]
    NodeAffinity,
    #[serde(rename = "resource-affinity")]
    ResourceAffinity,

}

impl std::fmt::Display for PveClusterHaTypeTypeEnum2 {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::NodeAffinity => write!(f, "node-affinity"),
            Self::ResourceAffinity => write!(f, "resource-affinity"),
        }
    }
}

impl Default for PveClusterHaTypeTypeEnum2 {
    fn default() -> PveClusterHaTypeTypeEnum2 {
        Self::NodeAffinity
    }
}

