/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveActionEnum {
    #[serde(rename = "permit")]
    Permit,
    #[serde(rename = "deny")]
    Deny,

}

impl std::fmt::Display for PveActionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Permit => write!(f, "permit"),
            Self::Deny => write!(f, "deny"),
        }
    }
}

impl Default for PveActionEnum {
    fn default() -> PveActionEnum {
        Self::Permit
    }
}

