/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveU2fConfig {

    /// U2F AppId URL override. Defaults to the origin.
    #[serde(rename = "appid", skip_serializing_if = "Option::is_none")]
    pub appid: Option<String>,

    /// U2F Origin override. Mostly useful for single nodes with a single URL.
    #[serde(rename = "origin", skip_serializing_if = "Option::is_none")]
    pub origin: Option<String>,


}

impl PveU2fConfig {
    pub fn new() -> PveU2fConfig {
        PveU2fConfig {
            
            appid: None,
            
            origin: None,
            
        }
    }
}


impl PveU2fConfig {
    /// Serialise this PveU2fConfig into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `PveU2fConfig `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        
        if let Some(ref v) = self.appid {
            parts.push(format!("appid={}", v));
        }
        
        
        if let Some(ref v) = self.origin {
            parts.push(format!("origin={}", v));
        }
        
        parts.join(",")
    }
}

