/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveRealmPveConfig {

    /// A list of audiences that the OpenID Issuer may include that are accepted in addition to 'client-id'.
    #[serde(rename = "audiences", skip_serializing_if = "Option::is_none")]
    pub audiences: Option<String>,

    /// Check bind connection to the server.
    #[serde(rename = "check-connection", skip_serializing_if = "Option::is_none")]
    pub check_connection: Option<models::PveBoolean>,

    /// Authentication domain ID
    #[serde(rename = "realm")]
    pub realm: String,

    /// Use this as default realm
    #[serde(rename = "default", skip_serializing_if = "Option::is_none")]
    pub default: Option<models::PveBoolean>,

    /// Description.
    #[serde(rename = "comment", skip_serializing_if = "Option::is_none")]
    pub comment: Option<String>,

    /// Use Two-factor authentication.
    #[serde(rename = "tfa", skip_serializing_if = "Option::is_none")]
    pub tfa: Option<String>,

    #[serde(rename = "type")]
    pub r#type: Type,


}

impl PveRealmPveConfig {
    pub fn new(realm: String, r#type: Type) -> PveRealmPveConfig {
        PveRealmPveConfig {
            
            audiences: None,
            
            check_connection: None,
            
            realm,
            
            default: None,
            
            comment: None,
            
            tfa: None,
            
            r#type,
            
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pve")]
    Pve,
}

impl Default for Type {
    fn default() -> Type {
        Self::Pve
    }
}

