/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PveQemuIdeField {
    PveQemuIdeConfig(Box<models::PveQemuIdeConfig>),
    String(String),
}

impl Default for PveQemuIdeField {
    fn default() -> Self {
        Self::PveQemuIdeConfig(Default::default())
    }
}

