/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveFormatFormatEnum {
    #[serde(rename = "raw")]
    Raw,
    #[serde(rename = "qcow2")]
    Qcow2,
    #[serde(rename = "subvol")]
    Subvol,
    #[serde(rename = "vmdk")]
    Vmdk,

}

impl std::fmt::Display for PveFormatFormatEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Raw => write!(f, "raw"),
            Self::Qcow2 => write!(f, "qcow2"),
            Self::Subvol => write!(f, "subvol"),
            Self::Vmdk => write!(f, "vmdk"),
        }
    }
}

impl Default for PveFormatFormatEnum {
    fn default() -> PveFormatFormatEnum {
        Self::Raw
    }
}

