/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveFileTypeEnum {
    #[serde(rename = "list")]
    List,
    #[serde(rename = "sources")]
    Sources,

}

impl std::fmt::Display for PveFileTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::List => write!(f, "list"),
            Self::Sources => write!(f, "sources"),
        }
    }
}

impl Default for PveFileTypeEnum {
    fn default() -> PveFileTypeEnum {
        Self::List
    }
}

