/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterNetworkTypeEnum {
    #[serde(rename = "fabric")]
    Fabric,
    #[serde(rename = "zone")]
    Zone,

}

impl std::fmt::Display for PveClusterNetworkTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Fabric => write!(f, "fabric"),
            Self::Zone => write!(f, "zone"),
        }
    }
}

impl Default for PveClusterNetworkTypeEnum {
    fn default() -> PveClusterNetworkTypeEnum {
        Self::Fabric
    }
}

