/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveFlagEnum {
    #[serde(rename = "nobackfill")]
    Nobackfill,
    #[serde(rename = "nodeep-scrub")]
    NodeepScrub,
    #[serde(rename = "nodown")]
    Nodown,
    #[serde(rename = "noin")]
    Noin,
    #[serde(rename = "noout")]
    Noout,
    #[serde(rename = "norebalance")]
    Norebalance,
    #[serde(rename = "norecover")]
    Norecover,
    #[serde(rename = "noscrub")]
    Noscrub,
    #[serde(rename = "notieragent")]
    Notieragent,
    #[serde(rename = "noup")]
    Noup,
    #[serde(rename = "pause")]
    Pause,

}

impl std::fmt::Display for PveFlagEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Nobackfill => write!(f, "nobackfill"),
            Self::NodeepScrub => write!(f, "nodeep-scrub"),
            Self::Nodown => write!(f, "nodown"),
            Self::Noin => write!(f, "noin"),
            Self::Noout => write!(f, "noout"),
            Self::Norebalance => write!(f, "norebalance"),
            Self::Norecover => write!(f, "norecover"),
            Self::Noscrub => write!(f, "noscrub"),
            Self::Notieragent => write!(f, "notieragent"),
            Self::Noup => write!(f, "noup"),
            Self::Pause => write!(f, "pause"),
        }
    }
}

impl Default for PveFlagEnum {
    fn default() -> PveFlagEnum {
        Self::Nobackfill
    }
}

