/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterCephScopeEnum {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "versions")]
    Versions,

}

impl std::fmt::Display for PveClusterCephScopeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::All => write!(f, "all"),
            Self::Versions => write!(f, "versions"),
        }
    }
}

impl Default for PveClusterCephScopeEnum {
    fn default() -> PveClusterCephScopeEnum {
        Self::All
    }
}

