/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum PveLinkField {
    PveLinkConfig(Box<models::PveLinkConfig>),
    String(String),
}

impl Default for PveLinkField {
    fn default() -> Self {
        Self::PveLinkConfig(Default::default())
    }
}

