/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterOptionsShapeEnum {
    #[serde(rename = "full")]
    Full,
    #[serde(rename = "circle")]
    Circle,
    #[serde(rename = "dense")]
    Dense,
    #[serde(rename = "none")]
    None,

}

impl std::fmt::Display for PveClusterOptionsShapeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Full => write!(f, "full"),
            Self::Circle => write!(f, "circle"),
            Self::Dense => write!(f, "dense"),
            Self::None => write!(f, "none"),
        }
    }
}

impl Default for PveClusterOptionsShapeEnum {
    fn default() -> PveClusterOptionsShapeEnum {
        Self::Full
    }
}

