/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PvePoolsTypeTypeEnum {
    #[serde(rename = "qemu")]
    Qemu,
    #[serde(rename = "lxc")]
    Lxc,
    #[serde(rename = "openvz")]
    Openvz,
    #[serde(rename = "storage")]
    Storage,

}

impl std::fmt::Display for PvePoolsTypeTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Qemu => write!(f, "qemu"),
            Self::Lxc => write!(f, "lxc"),
            Self::Openvz => write!(f, "openvz"),
            Self::Storage => write!(f, "storage"),
        }
    }
}

impl Default for PvePoolsTypeTypeEnum {
    fn default() -> PvePoolsTypeTypeEnum {
        Self::Qemu
    }
}

