/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterNotificationsTypeEnum {
    #[serde(rename = "sendmail")]
    Sendmail,
    #[serde(rename = "gotify")]
    Gotify,
    #[serde(rename = "smtp")]
    Smtp,
    #[serde(rename = "webhook")]
    Webhook,

}

impl std::fmt::Display for PveClusterNotificationsTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Sendmail => write!(f, "sendmail"),
            Self::Gotify => write!(f, "gotify"),
            Self::Smtp => write!(f, "smtp"),
            Self::Webhook => write!(f, "webhook"),
        }
    }
}

impl Default for PveClusterNotificationsTypeEnum {
    fn default() -> PveClusterNotificationsTypeEnum {
        Self::Sendmail
    }
}

