/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveNodesConfigPropertyEnum {
    #[serde(rename = "acme")]
    Acme,
    #[serde(rename = "acmedomain0")]
    Acmedomain0,
    #[serde(rename = "acmedomain1")]
    Acmedomain1,
    #[serde(rename = "acmedomain2")]
    Acmedomain2,
    #[serde(rename = "acmedomain3")]
    Acmedomain3,
    #[serde(rename = "acmedomain4")]
    Acmedomain4,
    #[serde(rename = "acmedomain5")]
    Acmedomain5,
    #[serde(rename = "ballooning-target")]
    BallooningTarget,
    #[serde(rename = "description")]
    Description,
    #[serde(rename = "location")]
    Location,
    #[serde(rename = "startall-onboot-delay")]
    StartallOnbootDelay,
    #[serde(rename = "wakeonlan")]
    Wakeonlan,

}

impl std::fmt::Display for PveNodesConfigPropertyEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Acme => write!(f, "acme"),
            Self::Acmedomain0 => write!(f, "acmedomain0"),
            Self::Acmedomain1 => write!(f, "acmedomain1"),
            Self::Acmedomain2 => write!(f, "acmedomain2"),
            Self::Acmedomain3 => write!(f, "acmedomain3"),
            Self::Acmedomain4 => write!(f, "acmedomain4"),
            Self::Acmedomain5 => write!(f, "acmedomain5"),
            Self::BallooningTarget => write!(f, "ballooning-target"),
            Self::Description => write!(f, "description"),
            Self::Location => write!(f, "location"),
            Self::StartallOnbootDelay => write!(f, "startall-onboot-delay"),
            Self::Wakeonlan => write!(f, "wakeonlan"),
        }
    }
}

impl Default for PveNodesConfigPropertyEnum {
    fn default() -> PveNodesConfigPropertyEnum {
        Self::Acme
    }
}

