/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveFeaturesConfig {

    /// Mount /sys in unprivileged containers as `rw` instead of `mixed`. This can break networking under newer (>= v245) systemd-network use.
    #[serde(rename = "force_rw_sys", skip_serializing_if = "Option::is_none")]
    pub force_rw_sys: Option<models::PveBoolean>,

    /// Allow using 'fuse' file systems in a container. Note that interactions between fuse and the freezer cgroup can potentially cause I/O deadlocks.
    #[serde(rename = "fuse", skip_serializing_if = "Option::is_none")]
    pub fuse: Option<models::PveBoolean>,

    /// For unprivileged containers only: Allow the use of the keyctl() system call. This is required to use docker inside a container. By default unprivileged containers will see this system call as non-existent. This is mostly a workaround for systemd-networkd, as it will treat it as a fatal error when some keyctl() operations are denied by the kernel due to lacking permissions. Essentially, you can choose between running systemd-networkd or docker.
    #[serde(rename = "keyctl", skip_serializing_if = "Option::is_none")]
    pub keyctl: Option<models::PveBoolean>,

    /// Allow unprivileged containers to use mknod() to add certain device nodes. This requires a kernel with seccomp trap to user space support (5.3 or newer). This is experimental.
    #[serde(rename = "mknod", skip_serializing_if = "Option::is_none")]
    pub mknod: Option<models::PveBoolean>,

    /// Allow mounting file systems of specific types. This should be a list of file system types as used with the mount command. Note that this can have negative effects on the container's security. With access to a loop device, mounting a file can circumvent the mknod permission of the devices cgroup, mounting an NFS file system can block the host's I/O completely and prevent it from rebooting, etc.
    #[serde(rename = "mount", skip_serializing_if = "Option::is_none")]
    pub mount: Option<String>,

    /// Allow nesting. Best used with unprivileged containers with additional id mapping. Note that this will expose procfs and sysfs contents of the host to the guest. This is also required by systemd to isolate services.
    #[serde(rename = "nesting", skip_serializing_if = "Option::is_none")]
    pub nesting: Option<models::PveBoolean>,


}

impl PveFeaturesConfig {
    pub fn new() -> PveFeaturesConfig {
        PveFeaturesConfig {
            
            force_rw_sys: None,
            
            fuse: None,
            
            keyctl: None,
            
            mknod: None,
            
            mount: None,
            
            nesting: None,
            
        }
    }
}


impl PveFeaturesConfig {
    /// Serialise this PveFeaturesConfig into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `PveFeaturesConfig `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        
        if let Some(ref v) = self.force_rw_sys {
            parts.push(format!("force_rw_sys={}", v));
        }
        
        
        if let Some(ref v) = self.fuse {
            parts.push(format!("fuse={}", v));
        }
        
        
        if let Some(ref v) = self.keyctl {
            parts.push(format!("keyctl={}", v));
        }
        
        
        if let Some(ref v) = self.mknod {
            parts.push(format!("mknod={}", v));
        }
        
        
        if let Some(ref v) = self.mount {
            parts.push(format!("mount={}", v));
        }
        
        
        if let Some(ref v) = self.nesting {
            parts.push(format!("nesting={}", v));
        }
        
        parts.join(",")
    }
}

