/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveSdnZoneSimpleConfig {

    /// the token for unlocking the global SDN configuration
    #[serde(rename = "lock-token", skip_serializing_if = "Option::is_none")]
    pub lock_token: Option<String>,

    /// Additional controllers.
    #[serde(rename = "secondary-controllers", skip_serializing_if = "Option::is_none")]
    pub secondary_controllers: Option<Vec<String>>,

    /// The SDN zone object identifier.
    #[serde(rename = "zone")]
    pub zone: String,

    /// List of cluster node names.
    #[serde(rename = "nodes", skip_serializing_if = "Option::is_none")]
    pub nodes: Option<String>,

    /// MTU of the zone, will be used for the created VNet bridges.
    #[serde(rename = "mtu", skip_serializing_if = "Option::is_none")]
    pub mtu: Option<i64>,

    /// dns api server
    #[serde(rename = "dns", skip_serializing_if = "Option::is_none")]
    pub dns: Option<String>,

    /// reverse dns api server
    #[serde(rename = "reversedns", skip_serializing_if = "Option::is_none")]
    pub reversedns: Option<String>,

    /// dns domain zone  ex: mydomain.com
    #[serde(rename = "dnszone", skip_serializing_if = "Option::is_none")]
    pub dnszone: Option<String>,

    /// use a specific ipam
    #[serde(rename = "ipam", skip_serializing_if = "Option::is_none")]
    pub ipam: Option<String>,

    /// Type of the DHCP backend for this zone
    #[serde(rename = "dhcp", skip_serializing_if = "Option::is_none")]
    pub dhcp: Option<models::PveDhcpEnum>,

    #[serde(rename = "type")]
    pub r#type: Type,


}

impl PveSdnZoneSimpleConfig {
    pub fn new(zone: String, r#type: Type) -> PveSdnZoneSimpleConfig {
        PveSdnZoneSimpleConfig {
            
            lock_token: None,
            
            secondary_controllers: None,
            
            zone,
            
            nodes: None,
            
            mtu: None,
            
            dns: None,
            
            reversedns: None,
            
            dnszone: None,
            
            ipam: None,
            
            dhcp: None,
            
            r#type,
            
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "simple")]
    Simple,
}

impl Default for Type {
    fn default() -> Type {
        Self::Simple
    }
}

