/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveQemuDeviceEnum {
    #[serde(rename = "ich9-intel-hda")]
    Ich9IntelHda,
    #[serde(rename = "intel-hda")]
    IntelHda,
    #[serde(rename = "AC97")]
    Ac97,

}

impl std::fmt::Display for PveQemuDeviceEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ich9IntelHda => write!(f, "ich9-intel-hda"),
            Self::IntelHda => write!(f, "intel-hda"),
            Self::Ac97 => write!(f, "AC97"),
        }
    }
}

impl Default for PveQemuDeviceEnum {
    fn default() -> PveQemuDeviceEnum {
        Self::Ich9IntelHda
    }
}

