/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PvePreallocationEnum {
    #[serde(rename = "off")]
    Off,
    #[serde(rename = "metadata")]
    Metadata,
    #[serde(rename = "falloc")]
    Falloc,
    #[serde(rename = "full")]
    Full,

}

impl std::fmt::Display for PvePreallocationEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Off => write!(f, "off"),
            Self::Metadata => write!(f, "metadata"),
            Self::Falloc => write!(f, "falloc"),
            Self::Full => write!(f, "full"),
        }
    }
}

impl Default for PvePreallocationEnum {
    fn default() -> PvePreallocationEnum {
        Self::Off
    }
}

