/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveResourceModeEnum {
    #[serde(rename = "freeze")]
    Freeze,
    #[serde(rename = "ignore")]
    Ignore,

}

impl std::fmt::Display for PveResourceModeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Freeze => write!(f, "freeze"),
            Self::Ignore => write!(f, "ignore"),
        }
    }
}

impl Default for PveResourceModeEnum {
    fn default() -> PveResourceModeEnum {
        Self::Freeze
    }
}

