/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveUnusedConfig {

    /// The volume that is not used currently.
    #[serde(rename = "volume")]
    pub volume: String,


}

impl PveUnusedConfig {
    pub fn new(volume: String) -> PveUnusedConfig {
        PveUnusedConfig {
            
            volume,
            
        }
    }
}


impl PveUnusedConfig {
    /// Serialise this PveUnusedConfig into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `PveUnusedConfig `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        parts.push(format!("{}", self.volume));
        
        
        
        parts.join(",")
    }
}

