/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveLogRatelimitConfig {

    /// Initial burst of packages which will always get logged before the rate is applied
    #[serde(rename = "burst", skip_serializing_if = "Option::is_none")]
    pub burst: Option<i64>,

    /// Enable or disable log rate limiting
    #[serde(rename = "enable")]
    pub enable: models::PveBoolean,

    /// Frequency with which the burst bucket gets refilled
    #[serde(rename = "rate", skip_serializing_if = "Option::is_none")]
    pub rate: Option<String>,


}

impl PveLogRatelimitConfig {
    pub fn new(enable: models::PveBoolean) -> PveLogRatelimitConfig {
        PveLogRatelimitConfig {
            
            burst: None,
            
            enable,
            
            rate: None,
            
        }
    }
}


impl PveLogRatelimitConfig {
    /// Serialise this PveLogRatelimitConfig into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `PveLogRatelimitConfig `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        parts.push(format!("{}", self.enable));
        
        
        
        
        if let Some(ref v) = self.burst {
            parts.push(format!("burst={}", v));
        }
        
        
        if let Some(ref v) = self.rate {
            parts.push(format!("rate={}", v));
        }
        
        parts.join(",")
    }
}

