/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveAudioConfig {

    /// Configure an audio device.
    #[serde(rename = "device")]
    pub device: models::PveQemuDeviceEnum,

    /// Driver backend for the audio device.
    #[serde(rename = "driver", skip_serializing_if = "Option::is_none")]
    pub driver: Option<models::PveDriverEnum>,


}

impl PveAudioConfig {
    pub fn new(device: models::PveQemuDeviceEnum) -> PveAudioConfig {
        PveAudioConfig {
            
            device,
            
            driver: None,
            
        }
    }
}


impl PveAudioConfig {
    /// Serialise this PveAudioConfig into Proxmox's CLI-style shorthand
    /// string (`key=value,…`). The property marked `x-pve-default-key`
    /// is emitted positionally without a `key=` prefix; aliases collapse
    /// multiple property names to the same wire key.
    ///
    /// Example: `PveAudioConfig `
    /// → `"virtio,bridge=vmbr0"`
    pub fn to_shorthand(&self) -> String {
        let mut parts: Vec<String> = Vec::new();
        
        
        
        parts.push(format!("device={}", self.device));
        
        
        
        if let Some(ref v) = self.driver {
            parts.push(format!("driver={}", v));
        }
        
        parts.join(",")
    }
}

