/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveClusterOptionsOrderingEnum {
    #[serde(rename = "config")]
    Config,
    #[serde(rename = "alphabetical")]
    Alphabetical,

}

impl std::fmt::Display for PveClusterOptionsOrderingEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Config => write!(f, "config"),
            Self::Alphabetical => write!(f, "alphabetical"),
        }
    }
}

impl Default for PveClusterOptionsOrderingEnum {
    fn default() -> PveClusterOptionsOrderingEnum {
        Self::Config
    }
}

