/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveSdnIpamPhpipamConfig {

    #[serde(rename = "url")]
    pub url: String,

    #[serde(rename = "token")]
    pub token: String,

    #[serde(rename = "section")]
    pub section: i64,

    /// Certificate SHA 256 fingerprint.
    #[serde(rename = "fingerprint", skip_serializing_if = "Option::is_none")]
    pub fingerprint: Option<String>,

    #[serde(rename = "type")]
    pub r#type: Type,


}

impl PveSdnIpamPhpipamConfig {
    pub fn new(url: String, token: String, section: i64, r#type: Type) -> PveSdnIpamPhpipamConfig {
        PveSdnIpamPhpipamConfig {
            
            url,
            
            token,
            
            section,
            
            fingerprint: None,
            
            r#type,
            
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "phpipam")]
    Phpipam,
}

impl Default for Type {
    fn default() -> Type {
        Self::Phpipam
    }
}

