/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PveSdnIpamPveConfig {

    /// The SDN ipam object identifier.
    #[serde(rename = "ipam")]
    pub ipam: String,

    /// the token for unlocking the global SDN configuration
    #[serde(rename = "lock-token", skip_serializing_if = "Option::is_none")]
    pub lock_token: Option<String>,

    #[serde(rename = "type")]
    pub r#type: Type,


}

impl PveSdnIpamPveConfig {
    pub fn new(ipam: String, r#type: Type) -> PveSdnIpamPveConfig {
        PveSdnIpamPveConfig {
            
            ipam,
            
            lock_token: None,
            
            r#type,
            
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "pve")]
    Pve,
}

impl Default for Type {
    fn default() -> Type {
        Self::Pve
    }
}

