/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveNodesDisksRaidlevelEnum {
    #[serde(rename = "single")]
    Single,
    #[serde(rename = "mirror")]
    Mirror,
    #[serde(rename = "raid10")]
    Raid10,
    #[serde(rename = "raidz")]
    Raidz,
    #[serde(rename = "raidz2")]
    Raidz2,
    #[serde(rename = "raidz3")]
    Raidz3,
    #[serde(rename = "draid")]
    Draid,
    #[serde(rename = "draid2")]
    Draid2,
    #[serde(rename = "draid3")]
    Draid3,

}

impl std::fmt::Display for PveNodesDisksRaidlevelEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Single => write!(f, "single"),
            Self::Mirror => write!(f, "mirror"),
            Self::Raid10 => write!(f, "raid10"),
            Self::Raidz => write!(f, "raidz"),
            Self::Raidz2 => write!(f, "raidz2"),
            Self::Raidz3 => write!(f, "raidz3"),
            Self::Draid => write!(f, "draid"),
            Self::Draid2 => write!(f, "draid2"),
            Self::Draid3 => write!(f, "draid3"),
        }
    }
}

impl Default for PveNodesDisksRaidlevelEnum {
    fn default() -> PveNodesDisksRaidlevelEnum {
        Self::Single
    }
}

