/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveOriginEnum {
    #[serde(rename = "user-created")]
    UserCreated,
    #[serde(rename = "builtin")]
    Builtin,
    #[serde(rename = "modified-builtin")]
    ModifiedBuiltin,

}

impl std::fmt::Display for PveOriginEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::UserCreated => write!(f, "user-created"),
            Self::Builtin => write!(f, "builtin"),
            Self::ModifiedBuiltin => write!(f, "modified-builtin"),
        }
    }
}

impl Default for PveOriginEnum {
    fn default() -> PveOriginEnum {
        Self::UserCreated
    }
}

