/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 9.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum PveProtocolEnum {
    #[serde(rename = "openfabric")]
    Openfabric,
    #[serde(rename = "ospf")]
    Ospf,
    #[serde(rename = "wireguard")]
    Wireguard,
    #[serde(rename = "bgp")]
    Bgp,

}

impl std::fmt::Display for PveProtocolEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Openfabric => write!(f, "openfabric"),
            Self::Ospf => write!(f, "ospf"),
            Self::Wireguard => write!(f, "wireguard"),
            Self::Bgp => write!(f, "bgp"),
        }
    }
}

impl Default for PveProtocolEnum {
    fn default() -> PveProtocolEnum {
        Self::Openfabric
    }
}

