/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QemuVmResetRequest {

    /// Ignore locks - only root is allowed to use this option.
    #[serde(rename = "skiplock", skip_serializing_if = "Option::is_none")]
    pub skiplock: Option<models::PveBoolean>,


}

impl QemuVmResetRequest {
    pub fn new() -> QemuVmResetRequest {
        QemuVmResetRequest {
            
            skiplock: None,
            
        }
    }
}


