/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct QemuExecStatusResponseData {

    /// stderr of the process
    #[serde(rename = "err-data", skip_serializing_if = "Option::is_none")]
    pub err_data: Option<String>,

    /// true if stderr was not fully captured
    #[serde(rename = "err-truncated", skip_serializing_if = "Option::is_none")]
    pub err_truncated: Option<models::PveBoolean>,

    /// process exit code if it was normally terminated.
    #[serde(rename = "exitcode", skip_serializing_if = "Option::is_none")]
    pub exitcode: Option<i64>,

    /// Tells if the given command has exited yet.
    #[serde(rename = "exited")]
    pub exited: models::PveBoolean,

    /// stdout of the process
    #[serde(rename = "out-data", skip_serializing_if = "Option::is_none")]
    pub out_data: Option<String>,

    /// true if stdout was not fully captured
    #[serde(rename = "out-truncated", skip_serializing_if = "Option::is_none")]
    pub out_truncated: Option<models::PveBoolean>,

    /// signal number or exception code if the process was abnormally terminated.
    #[serde(rename = "signal", skip_serializing_if = "Option::is_none")]
    pub signal: Option<i64>,


}

impl QemuExecStatusResponseData {
    pub fn new(exited: models::PveBoolean) -> QemuExecStatusResponseData {
        QemuExecStatusResponseData {
            
            err_data: None,
            
            err_truncated: None,
            
            exitcode: None,
            
            exited,
            
            out_data: None,
            
            out_truncated: None,
            
            signal: None,
            
        }
    }
}


