/*
 * Proxmox Virtual Environment API
 *
 * Generated from apidoc.js. NOT an official Proxmox specification. See https://pve.proxmox.com/pve-docs/api-viewer/ for the upstream documentation.
 *
 * The version of the OpenAPI document: 8.x
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StorageCreateStorageResponseData {

    #[serde(rename = "config", skip_serializing_if = "Option::is_none")]
    pub config: Option<Box<models::StorageCreateStorageResponseDataConfig>>,

    /// The ID of the created storage.
    #[serde(rename = "storage")]
    pub storage: String,

    /// The type of the created storage.
    #[serde(rename = "type")]
    pub r#type: models::PveStorageTypeEnum,


}

impl StorageCreateStorageResponseData {
    pub fn new(storage: String, r#type: models::PveStorageTypeEnum) -> StorageCreateStorageResponseData {
        StorageCreateStorageResponseData {
            
            config: None,
            
            storage,
            
            r#type,
            
        }
    }
}


